"""add mirror base url to test

Revision ID: 091da85970cb
Revises: 88e49e681048
Create Date: 2024-07-05 13:54:38.206076

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "091da85970cb"
down_revision = "88e49e681048"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_mirror_base_url"), "mirror", ["base_url"])
    op.add_column("test", sa.Column("mirror_url", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_test_mirror_url_mirror"),
        "test",
        "mirror",
        ["mirror_url"],
        ["base_url"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_test_mirror_url_mirror"), "test", type_="foreignkey")
    op.drop_column("test", "mirror_url")
    op.drop_constraint(op.f("uq_mirror_base_url"), "mirror", type_="unique")
    # ### end Alembic commands ###
