"""set up many-to-many table for worker and country

Revision ID: 1e455d030d80
Revises: 40f7e2866f5d
Create Date: 2024-07-15 13:33:11.070559

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1e455d030d80"
down_revision = "40f7e2866f5d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_country",
        sa.Column("worker_id", sa.String(), nullable=False),
        sa.Column("country_code", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk_worker_country_country_code_country"),
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.id"],
            name=op.f("fk_worker_country_worker_id_worker"),
        ),
        sa.PrimaryKeyConstraint(
            "worker_id", "country_code", name=op.f("pk_worker_country")
        ),
    )
    op.drop_constraint("fk_country_worker_id_worker", "country", type_="foreignkey")
    op.drop_column("country", "worker_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "country",
        sa.Column("worker_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "fk_country_worker_id_worker", "country", "worker", ["worker_id"], ["id"]
    )
    op.drop_table("worker_country")
    # ### end Alembic commands ###
