"""add location for tests

Revision ID: 40f7e2866f5d
Revises: e1f384f65fcc
Create Date: 2024-07-08 11:50:01.976211

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "40f7e2866f5d"
down_revision = "e1f384f65fcc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_location")),
    )
    op.alter_column("test", "location", new_column_name="city")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("test", "city", new_column_name="location")
    op.drop_table("location")
    # ### end Alembic commands ###
