"""add worker_id to tests

Revision ID: 5c376f6fb191
Revises: 0c273daa1ab0
Create Date: 2024-06-13 12:22:45.194845

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c376f6fb191"
down_revision = "0c273daa1ab0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test", sa.Column("worker_id", sa.String(), nullable=True))
    op.create_foreign_key(
        op.f("fk_test_worker_id_worker"), "test", "worker", ["worker_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_test_worker_id_worker"), "test", type_="foreignkey")
    op.drop_column("test", "worker_id")
    # ### end Alembic commands ###
