"""set up database models

Revision ID: d45beab913d1
Revises:
Create Date: 2024-06-03 07:46:35.661038

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d45beab913d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "test",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("requested_on", sa.DateTime(), nullable=False),
        sa.Column("started_on", sa.DateTime(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(name="status", native_enum=False, create_constraint=True),
            nullable=True,
        ),
        sa.Column("error", postgresql.CITEXT(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("asn", postgresql.CITEXT(), nullable=True),
        sa.Column("location", postgresql.CITEXT(), nullable=True),
        sa.Column("latency", sa.Integer(), nullable=True),
        sa.Column("download_size", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_test")),
    )
    op.create_table(
        "worker",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("auth_info", postgresql.CITEXT(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker")),
    )
    op.create_table(
        "country",
        sa.Column("code", postgresql.CITEXT(), nullable=False),
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("worker_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["worker_id"], ["worker.id"], name=op.f("fk_country_worker_id_worker")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_country")),
        sa.UniqueConstraint("name", "code", name=op.f("uq_country_name")),
    )
    op.create_table(
        "mirror",
        sa.Column("base_url", postgresql.CITEXT(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", postgresql.CITEXT(), nullable=True),
        sa.Column("region", postgresql.CITEXT(), nullable=True),
        sa.Column("asn", postgresql.CITEXT(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("country_only", sa.Boolean(), nullable=True),
        sa.Column("region_only", sa.Boolean(), nullable=True),
        sa.Column("as_only", sa.Boolean(), nullable=True),
        sa.Column(
            "other_countries", postgresql.ARRAY(postgresql.CITEXT()), nullable=True
        ),
        sa.Column("country_code", postgresql.CITEXT(), nullable=False),
        sa.ForeignKeyConstraint(
            ["country_code"],
            ["country.code"],
            name=op.f("fk_mirror_country_code_country"),
        ),
        sa.PrimaryKeyConstraint("base_url", name=op.f("pk_mirror")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("mirror")
    op.drop_table("country")
    op.drop_table("worker")
    op.drop_table("test")
    # ### end Alembic commands ###
