name: Backend QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-qa:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: backend/pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: backend
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]

      - name: Check black formatting
        working-directory: backend
        run: inv lint-black

      - name: Check ruff
        working-directory: backend
        run: inv lint-ruff

      - name: Check pyright
        working-directory: backend
        run: inv check-pyright
