name: Publish backend Docker image

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main
  workflow_dispatch:

jobs:

  publish-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/mirrors-qa-backend
          on-master: latest
          restrict-to: kiwix/mirrors-qa
          context: backend
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
      - name: Deploy API changes on k8s
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.MIRRORSQA_KUBE_CONFIG }}
        with:
          args: rollout restart deployments api-deployment scheduler-deployment -n mirrors-qa
