name: Publish worker-manager Docker image

on:
  push:
    paths:
      - 'worker/**'
    branches:
      - main

jobs:

  publish-worker-manager:
    runs-on: ubuntu-22.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/mirrors-qa-worker-manager
          latest-on-tag: true
          tag-pattern: /^v([0-9.]+)$/
          restrict-to: kiwix/mirrors-qa
          context: worker
          dockerfile: manager.Dockerfile
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
