name: Publish worker-task Docker image

on:
  push:
    paths:
      - 'worker/task/**'
    branches:
      - main

jobs:

  publish-worker-task:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/mirrors-qa-task-worker
          on-master: latest
          restrict-to: kiwix/mirrors-qa
          context: worker/task
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
