name: Publish worker-manager Docker image

on:
  push:
    paths:
      - 'worker/manager/**'
    branches:
      - main
    workflow_dispatch:

jobs:

  publish-worker-manager:
    runs-on: ubuntu-24.04
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/mirrors-qa-worker-manager
          on-master: latest
          restrict-to: kiwix/mirrors-qa
          context: worker/manager
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
