name: Publish worker-manager Docker image

on:
  push:
    branches:
      - 'main'

jobs:

  paths-filter:
    runs-on: ubuntu-22.04

    outputs:
      worker_manager: ${{ steps.filter.outputs.worker_manager }}

    steps:
    - uses: actions/checkout@v4

    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          worker_manager:
            - 'worker/**'

  publish-worker-manager:
    runs-on: ubuntu-22.04
    needs: paths-filter
    # run only if 'worker' files were changed
    if: needs.paths-filter.outputs.worker_manager == 'true'
    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/mirrors-qa-worker-manager
          latest-on-tag: true
          tag-pattern: /^v([0-9.]+)$/
          restrict-to: openzim/mirrors-qa
          context: worker
          dockerfile: manager.Dockerfile
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
