name: Worker Manager QA

on:
  pull_request:
  push:
    paths:
      - 'worker/manager/**'
    branches:
      - main

jobs:

  check-qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version-file: worker/manager/pyproject.toml
          architecture: x64

      - name: Install dependencies (and project)
        working-directory: worker/manager
        run: |
          pip install -U pip
          pip install -e .[lint,scripts,test,check]

      - name: Check black formatting
        working-directory: worker/manager
        run: inv lint-black

      - name: Check ruff
        working-directory: worker/manager
        run: inv lint-ruff

      - name: Check pyright
        working-directory: worker/manager
        run: inv check-pyright
